/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <bonobo.h>
#include <gnome.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

static GnomeUIInfo file1_menu_uiinfo[] =
{
  GNOMEUIINFO_MENU_NEW_ITEM (N_("_New"), N_("New source file"), on_new1_activate, NULL),
  GNOMEUIINFO_MENU_OPEN_ITEM (on_open1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_ITEM (on_save1_activate, NULL),
  GNOMEUIINFO_MENU_SAVE_AS_ITEM (on_save_as1_activate, NULL),
  GNOMEUIINFO_SEPARATOR,
  GNOMEUIINFO_MENU_EXIT_ITEM (on_quit1_activate, NULL),
  GNOMEUIINFO_END
};

static GnomeUIInfo reset1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Registers"),
    NULL,
    (gpointer) on_registers1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Flags"),
    NULL,
    (gpointer) on_flags1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("IO Ports"),
    NULL,
    (gpointer) on_io_ports1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Main Memory"),
    NULL,
    (gpointer) on_main_memory1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Reset all"),
    NULL,
    (gpointer) on_reset_all1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo _8085_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_Reset"),
    N_("Reset Microprocessor"),
    reset1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-no",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo assembler1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Assemble"),
    N_("Only assemble the program"),
    (gpointer) on_assemble1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-convert",
    GDK_F11, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("E_xecute"),
    N_("Execute assembled and loaded program"),
    (gpointer) on_execute1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-execute",
    GDK_F4, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Show _listing"),
    N_("Show the source code along with opcodes and operands in hex numbers"),
    (gpointer) on_show_listing1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gnome-stock-text-bulleted-list",
    GDK_L, (GdkModifierType) GDK_CONTROL_MASK | GDK_SHIFT_MASK, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo breakpoints1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Toggle breakpoint"),
    N_("Toggles breakpoint at current line"),
    (gpointer) on_toggle_breakpoint1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gnome-stock-attach",
    GDK_B, (GdkModifierType) GDK_CONTROL_MASK, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_Clear all breakpoints"),
    N_("Remove all breakpoints"),
    (gpointer) on_clear_all_breakpoints1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo debug1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("Step _in"),
    N_("Step in the code"),
    (gpointer) on_step_in1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-jump-to",
    GDK_F5, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Step o_ver"),
    N_("Step over the code without calling functions"),
    (gpointer) on_step_over1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-jump-to",
    GDK_F6, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("Step _out"),
    N_("Step out of the current function"),
    (gpointer) on_step_out1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-jump-to",
    GDK_F7, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_SUBTREE, N_("_Breakpoints"),
    N_("Add or remove breakpoints"),
    breakpoints1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gnome-stock-attach",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("Stop execution"),
    N_("Stop debugging"),
    (gpointer) on_stop_execution1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-stop",
    GDK_E, (GdkModifierType) GDK_CONTROL_MASK, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo help1_menu_uiinfo[] =
{
  {
    GNOME_APP_UI_ITEM, N_("_Help"),
    NULL,
    (gpointer) on_help_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-help",
    GDK_F1, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_8085 manual"),
    NULL,
    (gpointer) on_8085_manual1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-dialog-info",
    GDK_F1, (GdkModifierType) GDK_CONTROL_MASK, NULL
  },
  {
    GNOME_APP_UI_ITEM, N_("_Assembler reference"),
    NULL,
    (gpointer) on_assembler_reference1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gtk-dialog-info",
    GDK_F1, (GdkModifierType) GDK_SHIFT_MASK, NULL
  },
  GNOMEUIINFO_SEPARATOR,
  {
    GNOME_APP_UI_ITEM, N_("_About"),
    N_("About this program"),
    (gpointer) on_about1_activate, NULL, NULL,
    GNOME_APP_PIXMAP_STOCK, "gnome-stock-about",
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

static GnomeUIInfo menubar1_uiinfo[] =
{
  {
    GNOME_APP_UI_SUBTREE, N_("_File"),
    NULL,
    file1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_8085"),
    NULL,
    _8085_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Assembler"),
    N_("Do assembling stuffs"),
    assembler1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Debug"),
    N_("Debug your program"),
    debug1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  {
    GNOME_APP_UI_SUBTREE, N_("_Help"),
    NULL,
    help1_menu_uiinfo, NULL, NULL,
    GNOME_APP_PIXMAP_NONE, NULL,
    0, (GdkModifierType) 0, NULL
  },
  GNOMEUIINFO_END
};

GtkWidget*
create_window_main (void)
{
  GtkWidget *window_main;
  GdkPixbuf *window_main_icon_pixbuf;
  GtkWidget *vbox1;
  GtkWidget *menubar1;
  GtkWidget *handlebox1;
  GtkWidget *toolbar1;
  GtkWidget *new1_t;
  GtkWidget *open1_t;
  GtkWidget *save1_t;
  GtkWidget *save_as1_t;
  GtkWidget *vseparator1;
  GtkWidget *tmp_toolbar_icon;
  GtkWidget *assemble1_tb;
  GtkWidget *execute1_tb;
  GtkWidget *vseparator2;
  GtkWidget *button7;
  GtkWidget *button8;
  GtkWidget *button9;
  GtkWidget *vseparator3;
  GtkWidget *button11;
  GtkWidget *stop_execution1_tb;
  GtkWidget *main_hpaned_left;
  GtkWidget *vbox9;
  GtkWidget *hbox15;
  GtkWidget *frame9;
  GtkWidget *table7;
  GtkWidget *label107;
  GtkWidget *label108;
  GtkWidget *label109;
  GtkWidget *label110;
  GtkWidget *label111;
  GtkWidget *label112;
  GtkWidget *label113;
  GtkWidget *main_reg_a;
  GtkWidget *main_reg_b;
  GtkWidget *main_reg_c;
  GtkWidget *main_reg_d;
  GtkWidget *main_reg_e;
  GtkWidget *main_reg_h;
  GtkWidget *main_reg_l;
  GtkWidget *main_reg_pswh;
  GtkWidget *main_reg_pswl;
  GtkWidget *main_reg_pch;
  GtkWidget *main_reg_pcl;
  GtkWidget *main_reg_sph;
  GtkWidget *main_reg_spl;
  GtkWidget *main_reg_int_reg;
  GtkWidget *label106;
  GtkWidget *hbox34;
  GtkWidget *image365;
  GtkWidget *label96;
  GtkWidget *frame10;
  GtkWidget *table8;
  GtkWidget *label129;
  GtkWidget *label130;
  GtkWidget *label131;
  GtkWidget *label132;
  GtkWidget *label133;
  GtkWidget *main_flag_s;
  GtkWidget *main_flag_z;
  GtkWidget *main_flag_ac;
  GtkWidget *main_flag_p;
  GtkWidget *main_flag_c;
  GtkWidget *hbox35;
  GtkWidget *image366;
  GtkWidget *label163;
  GtkWidget *frame12;
  GtkWidget *hbox29;
  GtkWidget *vbox13;
  GtkWidget *label154;
  GtkWidget *main_entry_dec;
  GtkWidget *main_but_to_hex;
  GtkWidget *alignment7;
  GtkWidget *hbox30;
  GtkWidget *image293;
  GtkWidget *label156;
  GtkWidget *vbox14;
  GtkWidget *label155;
  GtkWidget *main_entry_hex;
  GtkWidget *main_but_to_dec;
  GtkWidget *alignment8;
  GtkWidget *hbox31;
  GtkWidget *image294;
  GtkWidget *label157;
  GtkWidget *hbox38;
  GtkWidget *image369;
  GtkWidget *label153;
  GtkWidget *vbox10;
  GtkWidget *frame6;
  GtkWidget *vbox11;
  GtkWidget *hbox13;
  GtkObject *main_io_spin_adj;
  GtkWidget *main_io_spin;
  GtkWidget *main_io_entry;
  GtkWidget *main_io_update;
  GtkWidget *alignment4;
  GtkWidget *hbox16;
  GtkWidget *image226;
  GtkWidget *label139;
  GtkWidget *hbox36;
  GtkWidget *image367;
  GtkWidget *label164;
  GtkWidget *frame8;
  GtkWidget *vbox12;
  GtkWidget *hbox14;
  GtkObject *main_mem_spin_adj;
  GtkWidget *main_mem_spin;
  GtkWidget *main_mem_entry;
  GtkWidget *main_mem_update;
  GtkWidget *alignment5;
  GtkWidget *hbox17;
  GtkWidget *image227;
  GtkWidget *label140;
  GtkWidget *hbox37;
  GtkWidget *image368;
  GtkWidget *label165;
  GtkWidget *main_vpaned_msg;
  GtkWidget *main_hpaned_data;
  GtkWidget *main_vbox_center;
  GtkWidget *hbox24;
  GtkWidget *label147;
  GtkWidget *main_entry_sa;
  GtkWidget *notebook5;
  GtkWidget *main_frame_data;
  GtkWidget *main_data_scroll;
  GtkWidget *label150;
  GtkWidget *hbox25;
  GtkWidget *image232;
  GtkWidget *label148;
  GtkWidget *frame11;
  GtkWidget *main_stack_scroll;
  GtkWidget *label152;
  GtkWidget *hbox26;
  GtkWidget *image233;
  GtkWidget *label149;
  GtkWidget *frame14;
  GtkWidget *main_keypad_scroll;
  GtkWidget *label169;
  GtkWidget *hbox40;
  GtkWidget *image371;
  GtkWidget *label168;
  GtkWidget *main_appbar;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window_main = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_main), _("GNUSim8085 - 8085 Microprocessor Simulator"));
  gtk_window_set_position (GTK_WINDOW (window_main), GTK_WIN_POS_CENTER);
  gtk_window_set_default_size (GTK_WINDOW (window_main), 500, 400);
  window_main_icon_pixbuf = create_pixbuf ("gnusim8085_icon.png");
  if (window_main_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window_main), window_main_icon_pixbuf);
      gdk_pixbuf_unref (window_main_icon_pixbuf);
    }

  vbox1 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (window_main), vbox1);

  menubar1 = gtk_menu_bar_new ();
  gtk_widget_show (menubar1);
  gtk_box_pack_start (GTK_BOX (vbox1), menubar1, FALSE, FALSE, 0);
  gnome_app_fill_menu (GTK_MENU_SHELL (menubar1), menubar1_uiinfo,
                       NULL, FALSE, 0);

  handlebox1 = gtk_handle_box_new ();
  gtk_widget_show (handlebox1);
  gtk_box_pack_start (GTK_BOX (vbox1), handlebox1, FALSE, TRUE, 0);

  toolbar1 = gtk_toolbar_new ();
  gtk_widget_show (toolbar1);
  gtk_container_add (GTK_CONTAINER (handlebox1), toolbar1);
  gtk_toolbar_set_style (GTK_TOOLBAR (toolbar1), GTK_TOOLBAR_ICONS);

  new1_t = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-new",
                                "gtk-new",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (new1_t);

  open1_t = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-open",
                                "gtk-open",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (open1_t);

  save1_t = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-save",
                                "gtk-save",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (save1_t);

  save_as1_t = gtk_toolbar_insert_stock (GTK_TOOLBAR (toolbar1),
                                "gtk-save-as",
                                "gtk-save-as",
                                NULL, NULL, NULL, -1);
  gtk_widget_show (save_as1_t);

  vseparator1 = gtk_vseparator_new ();
  gtk_widget_show (vseparator1);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), vseparator1, NULL, NULL);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-convert", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  assemble1_tb = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Assemble"),
                                _("Only assemble the program"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (assemble1_tb);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-execute", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  execute1_tb = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Execute"),
                                _("Execute program until breakpoint"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (execute1_tb);

  vseparator2 = gtk_vseparator_new ();
  gtk_widget_show (vseparator2);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), vseparator2, NULL, NULL);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-jump-to", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button7 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Step in"),
                                _("Step in"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (button7);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-jump-to", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button8 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Step over"),
                                _("Step over"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (button8);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-jump-to", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button9 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Step out"),
                                _("Step out"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (button9);

  vseparator3 = gtk_vseparator_new ();
  gtk_widget_show (vseparator3);
  gtk_toolbar_append_widget (GTK_TOOLBAR (toolbar1), vseparator3, NULL, NULL);

  gtk_toolbar_append_space (GTK_TOOLBAR (toolbar1));

  tmp_toolbar_icon = gtk_image_new_from_stock ("gnome-stock-attach", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  button11 = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Toggle breakpoint at current line"),
                                _("Toggle breakpoint"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (button11);

  tmp_toolbar_icon = gtk_image_new_from_stock ("gtk-stop", gtk_toolbar_get_icon_size (GTK_TOOLBAR (toolbar1)));
  stop_execution1_tb = gtk_toolbar_append_element (GTK_TOOLBAR (toolbar1),
                                GTK_TOOLBAR_CHILD_BUTTON,
                                NULL,
                                _("Stop execution"),
                                _("Stop debugging"), NULL,
                                tmp_toolbar_icon, NULL, NULL);
  gtk_label_set_use_underline (GTK_LABEL (((GtkToolbarChild*) (g_list_last (GTK_TOOLBAR (toolbar1)->children)->data))->label), TRUE);
  gtk_widget_show (stop_execution1_tb);
  gtk_widget_set_sensitive (stop_execution1_tb, FALSE);

  main_hpaned_left = gtk_hpaned_new ();
  gtk_widget_show (main_hpaned_left);
  gtk_box_pack_start (GTK_BOX (vbox1), main_hpaned_left, TRUE, TRUE, 0);
  gtk_paned_set_position (GTK_PANED (main_hpaned_left), 237);

  vbox9 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox9);
  gtk_paned_pack1 (GTK_PANED (main_hpaned_left), vbox9, FALSE, TRUE);

  hbox15 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox9), hbox15, FALSE, TRUE, 0);

  frame9 = gtk_frame_new (NULL);
  gtk_widget_show (frame9);
  gtk_box_pack_start (GTK_BOX (hbox15), frame9, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame9), 5);

  table7 = gtk_table_new (8, 3, TRUE);
  gtk_widget_show (table7);
  gtk_container_add (GTK_CONTAINER (frame9), table7);
  gtk_container_set_border_width (GTK_CONTAINER (table7), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table7), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table7), 6);

  label107 = gtk_label_new (_("<i>BC</i>"));
  gtk_widget_show (label107);
  gtk_table_attach (GTK_TABLE (table7), label107, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label107), TRUE);

  label108 = gtk_label_new (_("<i>DE</i>"));
  gtk_widget_show (label108);
  gtk_table_attach (GTK_TABLE (table7), label108, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label108), TRUE);

  label109 = gtk_label_new (_("<i>HL</i>"));
  gtk_widget_show (label109);
  gtk_table_attach (GTK_TABLE (table7), label109, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label109), TRUE);

  label110 = gtk_label_new (_("<i>PSW</i>"));
  gtk_widget_show (label110);
  gtk_table_attach (GTK_TABLE (table7), label110, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label110), TRUE);

  label111 = gtk_label_new (_("<i>PC</i>"));
  gtk_widget_show (label111);
  gtk_table_attach (GTK_TABLE (table7), label111, 0, 1, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label111), TRUE);

  label112 = gtk_label_new (_("<i>SP</i>"));
  gtk_widget_show (label112);
  gtk_table_attach (GTK_TABLE (table7), label112, 0, 1, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label112), TRUE);

  label113 = gtk_label_new (_("<i>Int-Reg</i>"));
  gtk_widget_show (label113);
  gtk_table_attach (GTK_TABLE (table7), label113, 0, 1, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label113), TRUE);

  main_reg_a = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_a);
  gtk_table_attach (GTK_TABLE (table7), main_reg_a, 1, 3, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_b = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_b);
  gtk_table_attach (GTK_TABLE (table7), main_reg_b, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_c = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_c);
  gtk_table_attach (GTK_TABLE (table7), main_reg_c, 2, 3, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_d = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_d);
  gtk_table_attach (GTK_TABLE (table7), main_reg_d, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_e = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_e);
  gtk_table_attach (GTK_TABLE (table7), main_reg_e, 2, 3, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_h = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_h);
  gtk_table_attach (GTK_TABLE (table7), main_reg_h, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_l = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_l);
  gtk_table_attach (GTK_TABLE (table7), main_reg_l, 2, 3, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_pswh = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_pswh);
  gtk_table_attach (GTK_TABLE (table7), main_reg_pswh, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_pswl = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_pswl);
  gtk_table_attach (GTK_TABLE (table7), main_reg_pswl, 2, 3, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_pch = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_pch);
  gtk_table_attach (GTK_TABLE (table7), main_reg_pch, 1, 2, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_pcl = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_pcl);
  gtk_table_attach (GTK_TABLE (table7), main_reg_pcl, 2, 3, 5, 6,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_sph = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_sph);
  gtk_table_attach (GTK_TABLE (table7), main_reg_sph, 1, 2, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_spl = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_spl);
  gtk_table_attach (GTK_TABLE (table7), main_reg_spl, 2, 3, 6, 7,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_reg_int_reg = gtk_label_new (_("00"));
  gtk_widget_show (main_reg_int_reg);
  gtk_table_attach (GTK_TABLE (table7), main_reg_int_reg, 1, 3, 7, 8,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  label106 = gtk_label_new (_("<i>A</i>"));
  gtk_widget_show (label106);
  gtk_table_attach (GTK_TABLE (table7), label106, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label106), TRUE);

  hbox34 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox34);
  gtk_frame_set_label_widget (GTK_FRAME (frame9), hbox34);

  image365 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image365);
  gtk_box_pack_start (GTK_BOX (hbox34), image365, TRUE, TRUE, 0);

  label96 = gtk_label_new (_("<b>Registers</b>"));
  gtk_widget_show (label96);
  gtk_box_pack_start (GTK_BOX (hbox34), label96, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label96), TRUE);
  gtk_label_set_justify (GTK_LABEL (label96), GTK_JUSTIFY_LEFT);

  frame10 = gtk_frame_new (NULL);
  gtk_widget_show (frame10);
  gtk_box_pack_start (GTK_BOX (hbox15), frame10, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame10), 5);

  table8 = gtk_table_new (5, 2, TRUE);
  gtk_widget_show (table8);
  gtk_container_add (GTK_CONTAINER (frame10), table8);
  gtk_container_set_border_width (GTK_CONTAINER (table8), 5);
  gtk_table_set_row_spacings (GTK_TABLE (table8), 10);
  gtk_table_set_col_spacings (GTK_TABLE (table8), 5);

  label129 = gtk_label_new (_("<i>S</i>"));
  gtk_widget_show (label129);
  gtk_table_attach (GTK_TABLE (table8), label129, 0, 1, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label129), TRUE);

  label130 = gtk_label_new (_("<i>Z</i>"));
  gtk_widget_show (label130);
  gtk_table_attach (GTK_TABLE (table8), label130, 0, 1, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label130), TRUE);

  label131 = gtk_label_new (_("<i>AC</i>"));
  gtk_widget_show (label131);
  gtk_table_attach (GTK_TABLE (table8), label131, 0, 1, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label131), TRUE);

  label132 = gtk_label_new (_("<i>P</i>"));
  gtk_widget_show (label132);
  gtk_table_attach (GTK_TABLE (table8), label132, 0, 1, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label132), TRUE);

  label133 = gtk_label_new (_("<i>C</i>"));
  gtk_widget_show (label133);
  gtk_table_attach (GTK_TABLE (table8), label133, 0, 1, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);
  gtk_label_set_use_markup (GTK_LABEL (label133), TRUE);

  main_flag_s = gtk_label_new (_("0"));
  gtk_widget_show (main_flag_s);
  gtk_table_attach (GTK_TABLE (table8), main_flag_s, 1, 2, 0, 1,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_flag_z = gtk_label_new (_("0"));
  gtk_widget_show (main_flag_z);
  gtk_table_attach (GTK_TABLE (table8), main_flag_z, 1, 2, 1, 2,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_flag_ac = gtk_label_new (_("0"));
  gtk_widget_show (main_flag_ac);
  gtk_table_attach (GTK_TABLE (table8), main_flag_ac, 1, 2, 2, 3,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_flag_p = gtk_label_new (_("0"));
  gtk_widget_show (main_flag_p);
  gtk_table_attach (GTK_TABLE (table8), main_flag_p, 1, 2, 3, 4,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  main_flag_c = gtk_label_new (_("0"));
  gtk_widget_show (main_flag_c);
  gtk_table_attach (GTK_TABLE (table8), main_flag_c, 1, 2, 4, 5,
                    (GtkAttachOptions) (GTK_FILL),
                    (GtkAttachOptions) (0), 0, 0);

  hbox35 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox35);
  gtk_frame_set_label_widget (GTK_FRAME (frame10), hbox35);

  image366 = gtk_image_new_from_stock ("gtk-sort-ascending", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image366);
  gtk_box_pack_start (GTK_BOX (hbox35), image366, TRUE, TRUE, 0);

  label163 = gtk_label_new (_("<b>Flag</b>"));
  gtk_widget_show (label163);
  gtk_box_pack_start (GTK_BOX (hbox35), label163, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label163), TRUE);
  gtk_label_set_justify (GTK_LABEL (label163), GTK_JUSTIFY_LEFT);

  frame12 = gtk_frame_new (NULL);
  gtk_widget_show (frame12);
  gtk_box_pack_start (GTK_BOX (vbox9), frame12, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame12), 5);

  hbox29 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox29);
  gtk_container_add (GTK_CONTAINER (frame12), hbox29);

  vbox13 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox13);
  gtk_box_pack_start (GTK_BOX (hbox29), vbox13, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox13), 5);

  label154 = gtk_label_new (_("Decimal"));
  gtk_widget_show (label154);
  gtk_box_pack_start (GTK_BOX (vbox13), label154, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label154), GTK_JUSTIFY_LEFT);

  main_entry_dec = gtk_entry_new ();
  gtk_widget_show (main_entry_dec);
  gtk_box_pack_start (GTK_BOX (vbox13), main_entry_dec, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, main_entry_dec, _("Enter a decimal number"), NULL);
  gtk_entry_set_text (GTK_ENTRY (main_entry_dec), _("0"));

  main_but_to_hex = gtk_button_new ();
  gtk_widget_show (main_but_to_hex);
  gtk_box_pack_start (GTK_BOX (vbox13), main_but_to_hex, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, main_but_to_hex, _("Convert this number to hexadecimal"), NULL);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (main_but_to_hex), alignment7);

  hbox30 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox30);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox30);

  image293 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image293);
  gtk_box_pack_start (GTK_BOX (hbox30), image293, FALSE, FALSE, 0);

  label156 = gtk_label_new_with_mnemonic (_("To Hex"));
  gtk_widget_show (label156);
  gtk_box_pack_start (GTK_BOX (hbox30), label156, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label156), GTK_JUSTIFY_LEFT);

  vbox14 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox14);
  gtk_box_pack_start (GTK_BOX (hbox29), vbox14, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox14), 5);

  label155 = gtk_label_new (_("Hex"));
  gtk_widget_show (label155);
  gtk_box_pack_start (GTK_BOX (vbox14), label155, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label155), GTK_JUSTIFY_LEFT);

  main_entry_hex = gtk_entry_new ();
  gtk_widget_show (main_entry_hex);
  gtk_box_pack_start (GTK_BOX (vbox14), main_entry_hex, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, main_entry_hex, _("Enter a hexadecimal number"), NULL);
  gtk_entry_set_text (GTK_ENTRY (main_entry_hex), _("0"));

  main_but_to_dec = gtk_button_new ();
  gtk_widget_show (main_but_to_dec);
  gtk_box_pack_start (GTK_BOX (vbox14), main_but_to_dec, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, main_but_to_dec, _("Convert this number to decimal"), NULL);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (main_but_to_dec), alignment8);

  hbox31 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox31);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox31);

  image294 = gtk_image_new_from_stock ("gtk-go-forward", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image294);
  gtk_box_pack_start (GTK_BOX (hbox31), image294, FALSE, FALSE, 0);

  label157 = gtk_label_new_with_mnemonic (_("To Dec"));
  gtk_widget_show (label157);
  gtk_box_pack_start (GTK_BOX (hbox31), label157, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label157), GTK_JUSTIFY_LEFT);

  hbox38 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox38);
  gtk_frame_set_label_widget (GTK_FRAME (frame12), hbox38);

  image369 = gtk_image_new_from_stock ("gtk-dialog-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image369);
  gtk_box_pack_start (GTK_BOX (hbox38), image369, TRUE, TRUE, 0);

  label153 = gtk_label_new (_("<b>Decimal - Hex Convertion</b>"));
  gtk_widget_show (label153);
  gtk_box_pack_start (GTK_BOX (hbox38), label153, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label153), TRUE);
  gtk_label_set_justify (GTK_LABEL (label153), GTK_JUSTIFY_LEFT);

  vbox10 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox10);
  gtk_box_pack_start (GTK_BOX (vbox9), vbox10, FALSE, TRUE, 0);

  frame6 = gtk_frame_new (NULL);
  gtk_widget_show (frame6);
  gtk_box_pack_start (GTK_BOX (vbox10), frame6, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame6), 5);

  vbox11 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox11);
  gtk_container_add (GTK_CONTAINER (frame6), vbox11);
  gtk_container_set_border_width (GTK_CONTAINER (vbox11), 5);

  hbox13 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox11), hbox13, TRUE, TRUE, 0);

  main_io_spin_adj = gtk_adjustment_new (0, 0, 255, 1, 10, 10);
  main_io_spin = gtk_spin_button_new (GTK_ADJUSTMENT (main_io_spin_adj), 1, 0);
  gtk_widget_show (main_io_spin);
  gtk_box_pack_start (GTK_BOX (hbox13), main_io_spin, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, main_io_spin, _("Change the port address to view here"), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (main_io_spin), TRUE);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (main_io_spin), TRUE);

  main_io_entry = gtk_entry_new ();
  gtk_widget_show (main_io_entry);
  gtk_box_pack_start (GTK_BOX (hbox13), main_io_entry, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, main_io_entry, _("Enter new port value and click Update"), NULL);
  gtk_entry_set_text (GTK_ENTRY (main_io_entry), _("0"));

  main_io_update = gtk_button_new ();
  gtk_widget_show (main_io_update);
  gtk_box_pack_start (GTK_BOX (vbox11), main_io_update, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, main_io_update, _("Update the port value"), NULL);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (main_io_update), alignment4);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox16);

  image226 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image226);
  gtk_box_pack_start (GTK_BOX (hbox16), image226, FALSE, FALSE, 0);

  label139 = gtk_label_new_with_mnemonic (_("Update Port Value"));
  gtk_widget_show (label139);
  gtk_box_pack_start (GTK_BOX (hbox16), label139, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label139), GTK_JUSTIFY_LEFT);

  hbox36 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox36);
  gtk_frame_set_label_widget (GTK_FRAME (frame6), hbox36);

  image367 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image367);
  gtk_box_pack_start (GTK_BOX (hbox36), image367, TRUE, TRUE, 0);

  label164 = gtk_label_new (_("<b>I/O Ports</b>"));
  gtk_widget_show (label164);
  gtk_box_pack_start (GTK_BOX (hbox36), label164, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label164), TRUE);
  gtk_label_set_justify (GTK_LABEL (label164), GTK_JUSTIFY_LEFT);

  frame8 = gtk_frame_new (NULL);
  gtk_widget_show (frame8);
  gtk_box_pack_start (GTK_BOX (vbox10), frame8, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame8), 5);

  vbox12 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox12);
  gtk_container_add (GTK_CONTAINER (frame8), vbox12);
  gtk_container_set_border_width (GTK_CONTAINER (vbox12), 5);

  hbox14 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox12), hbox14, TRUE, TRUE, 0);

  main_mem_spin_adj = gtk_adjustment_new (0, 0, 65535, 1, 10, 10);
  main_mem_spin = gtk_spin_button_new (GTK_ADJUSTMENT (main_mem_spin_adj), 1, 0);
  gtk_widget_show (main_mem_spin);
  gtk_box_pack_start (GTK_BOX (hbox14), main_mem_spin, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, main_mem_spin, _("Change the memory location to view here"), NULL);
  gtk_spin_button_set_numeric (GTK_SPIN_BUTTON (main_mem_spin), TRUE);
  gtk_spin_button_set_wrap (GTK_SPIN_BUTTON (main_mem_spin), TRUE);

  main_mem_entry = gtk_entry_new ();
  gtk_widget_show (main_mem_entry);
  gtk_box_pack_start (GTK_BOX (hbox14), main_mem_entry, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, main_mem_entry, _("Edit new value and click Update"), NULL);
  gtk_entry_set_text (GTK_ENTRY (main_mem_entry), _("0"));

  main_mem_update = gtk_button_new ();
  gtk_widget_show (main_mem_update);
  gtk_box_pack_start (GTK_BOX (vbox12), main_mem_update, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, main_mem_update, _("Update the current memory location"), NULL);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (main_mem_update), alignment5);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox17);

  image227 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image227);
  gtk_box_pack_start (GTK_BOX (hbox17), image227, FALSE, FALSE, 0);

  label140 = gtk_label_new_with_mnemonic (_("Update Memory"));
  gtk_widget_show (label140);
  gtk_box_pack_start (GTK_BOX (hbox17), label140, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label140), GTK_JUSTIFY_LEFT);

  hbox37 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox37);
  gtk_frame_set_label_widget (GTK_FRAME (frame8), hbox37);

  image368 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image368);
  gtk_box_pack_start (GTK_BOX (hbox37), image368, TRUE, TRUE, 0);

  label165 = gtk_label_new (_("<b>Memory</b>"));
  gtk_widget_show (label165);
  gtk_box_pack_start (GTK_BOX (hbox37), label165, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label165), TRUE);
  gtk_label_set_justify (GTK_LABEL (label165), GTK_JUSTIFY_LEFT);

  main_vpaned_msg = gtk_vpaned_new ();
  gtk_widget_show (main_vpaned_msg);
  gtk_paned_pack2 (GTK_PANED (main_hpaned_left), main_vpaned_msg, TRUE, FALSE);
  gtk_paned_set_position (GTK_PANED (main_vpaned_msg), 400);

  main_hpaned_data = gtk_hpaned_new ();
  gtk_widget_show (main_hpaned_data);
  gtk_paned_pack1 (GTK_PANED (main_vpaned_msg), main_hpaned_data, TRUE, FALSE);
  gtk_paned_set_position (GTK_PANED (main_hpaned_data), 400);

  main_vbox_center = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (main_vbox_center);
  gtk_paned_pack1 (GTK_PANED (main_hpaned_data), main_vbox_center, FALSE, FALSE);
  gtk_container_set_border_width (GTK_CONTAINER (main_vbox_center), 5);

  hbox24 = gtk_hbox_new (FALSE, 0);
  gtk_widget_show (hbox24);
  gtk_box_pack_start (GTK_BOX (main_vbox_center), hbox24, FALSE, FALSE, 5);

  label147 = gtk_label_new (_("Load me at"));
  gtk_widget_show (label147);
  gtk_box_pack_start (GTK_BOX (hbox24), label147, FALSE, FALSE, 5);
  gtk_label_set_justify (GTK_LABEL (label147), GTK_JUSTIFY_LEFT);

  main_entry_sa = gtk_entry_new ();
  gtk_widget_show (main_entry_sa);
  gtk_box_pack_start (GTK_BOX (hbox24), main_entry_sa, TRUE, TRUE, 0);
  gtk_tooltips_set_tip (tooltips, main_entry_sa, _("Enter the program address.  End with a 'h' if it is a hex address."), NULL);
  gtk_entry_set_max_length (GTK_ENTRY (main_entry_sa), 100);

  notebook5 = gtk_notebook_new ();
  gtk_widget_show (notebook5);
  gtk_paned_pack2 (GTK_PANED (main_hpaned_data), notebook5, TRUE, TRUE);

  main_frame_data = gtk_frame_new (NULL);
  gtk_widget_show (main_frame_data);
  gtk_container_add (GTK_CONTAINER (notebook5), main_frame_data);
  gtk_container_set_border_width (GTK_CONTAINER (main_frame_data), 5);

  main_data_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (main_data_scroll);
  gtk_container_add (GTK_CONTAINER (main_frame_data), main_data_scroll);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (main_data_scroll), GTK_SHADOW_OUT);

  label150 = gtk_label_new (_("Variables"));
  gtk_widget_show (label150);
  gtk_frame_set_label_widget (GTK_FRAME (main_frame_data), label150);
  gtk_label_set_justify (GTK_LABEL (label150), GTK_JUSTIFY_LEFT);

  hbox25 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox25);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 0), hbox25);

  image232 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image232);
  gtk_box_pack_start (GTK_BOX (hbox25), image232, TRUE, TRUE, 0);

  label148 = gtk_label_new (_("Data"));
  gtk_widget_show (label148);
  gtk_box_pack_start (GTK_BOX (hbox25), label148, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label148), GTK_JUSTIFY_LEFT);

  frame11 = gtk_frame_new (NULL);
  gtk_widget_show (frame11);
  gtk_container_add (GTK_CONTAINER (notebook5), frame11);
  gtk_container_set_border_width (GTK_CONTAINER (frame11), 5);

  main_stack_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (main_stack_scroll);
  gtk_container_add (GTK_CONTAINER (frame11), main_stack_scroll);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (main_stack_scroll), GTK_SHADOW_OUT);

  label152 = gtk_label_new (_("Stack Trace"));
  gtk_widget_show (label152);
  gtk_frame_set_label_widget (GTK_FRAME (frame11), label152);
  gtk_label_set_justify (GTK_LABEL (label152), GTK_JUSTIFY_LEFT);

  hbox26 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox26);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 1), hbox26);

  image233 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image233);
  gtk_box_pack_start (GTK_BOX (hbox26), image233, TRUE, TRUE, 0);

  label149 = gtk_label_new (_("Stack"));
  gtk_widget_show (label149);
  gtk_box_pack_start (GTK_BOX (hbox26), label149, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label149), GTK_JUSTIFY_LEFT);

  frame14 = gtk_frame_new (NULL);
  gtk_widget_show (frame14);
  gtk_container_add (GTK_CONTAINER (notebook5), frame14);
  gtk_container_set_border_width (GTK_CONTAINER (frame14), 5);

  main_keypad_scroll = gtk_scrolled_window_new (NULL, NULL);
  gtk_widget_show (main_keypad_scroll);
  gtk_container_add (GTK_CONTAINER (frame14), main_keypad_scroll);
  gtk_scrolled_window_set_shadow_type (GTK_SCROLLED_WINDOW (main_keypad_scroll), GTK_SHADOW_OUT);

  label169 = gtk_label_new (_("(KeyPad not yet stable.\nCheck out for v1.3)"));
  gtk_widget_show (label169);
  gtk_frame_set_label_widget (GTK_FRAME (frame14), label169);
  gtk_label_set_justify (GTK_LABEL (label169), GTK_JUSTIFY_LEFT);

  hbox40 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox40);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook5), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook5), 2), hbox40);

  image371 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image371);
  gtk_box_pack_start (GTK_BOX (hbox40), image371, TRUE, TRUE, 0);

  label168 = gtk_label_new (_("KeyPad"));
  gtk_widget_show (label168);
  gtk_box_pack_start (GTK_BOX (hbox40), label168, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label168), GTK_JUSTIFY_LEFT);

  main_appbar = gnome_appbar_new (TRUE, TRUE, GNOME_PREFERENCES_NEVER);
  gtk_widget_show (main_appbar);
  gtk_box_pack_end (GTK_BOX (vbox1), main_appbar, FALSE, TRUE, 0);

  g_signal_connect ((gpointer) window_main, "delete_event",
                    G_CALLBACK (on_window_main_delete_event),
                    NULL);
  g_signal_connect ((gpointer) new1_t, "clicked",
                    G_CALLBACK (on_new1_activate),
                    NULL);
  g_signal_connect ((gpointer) open1_t, "clicked",
                    G_CALLBACK (on_open1_activate),
                    NULL);
  g_signal_connect ((gpointer) save1_t, "clicked",
                    G_CALLBACK (on_save1_activate),
                    NULL);
  g_signal_connect ((gpointer) save_as1_t, "clicked",
                    G_CALLBACK (on_save_as1_activate),
                    NULL);
  g_signal_connect ((gpointer) assemble1_tb, "clicked",
                    G_CALLBACK (on_assemble1_activate),
                    NULL);
  g_signal_connect ((gpointer) execute1_tb, "clicked",
                    G_CALLBACK (on_execute1_activate),
                    NULL);
  g_signal_connect ((gpointer) button7, "clicked",
                    G_CALLBACK (on_step_in1_activate),
                    NULL);
  g_signal_connect ((gpointer) button8, "clicked",
                    G_CALLBACK (on_step_over1_activate),
                    NULL);
  g_signal_connect ((gpointer) button9, "clicked",
                    G_CALLBACK (on_step_out1_activate),
                    NULL);
  g_signal_connect ((gpointer) button11, "clicked",
                    G_CALLBACK (on_toggle_breakpoint1_activate),
                    NULL);
  g_signal_connect ((gpointer) stop_execution1_tb, "clicked",
                    G_CALLBACK (on_stop_execution1_activate),
                    NULL);
  g_signal_connect ((gpointer) main_entry_dec, "activate",
                    G_CALLBACK (on_main_entry_dec_activate),
                    NULL);
  g_signal_connect ((gpointer) main_but_to_hex, "clicked",
                    G_CALLBACK (on_main_but_to_hex_clicked),
                    NULL);
  g_signal_connect ((gpointer) main_entry_hex, "activate",
                    G_CALLBACK (on_main_entry_hex_activate),
                    NULL);
  g_signal_connect ((gpointer) main_but_to_dec, "clicked",
                    G_CALLBACK (on_main_but_to_dec_clicked),
                    NULL);
  g_signal_connect ((gpointer) main_io_spin, "changed",
                    G_CALLBACK (on_main_io_spin_changed),
                    NULL);
  g_signal_connect ((gpointer) main_io_update, "clicked",
                    G_CALLBACK (on_main_io_update_clicked),
                    NULL);
  g_signal_connect ((gpointer) main_mem_spin, "changed",
                    G_CALLBACK (on_main_mem_spin_changed),
                    NULL);
  g_signal_connect ((gpointer) main_mem_update, "clicked",
                    G_CALLBACK (on_main_mem_update_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_main, window_main, "window_main");
  GLADE_HOOKUP_OBJECT (window_main, vbox1, "vbox1");
  GLADE_HOOKUP_OBJECT (window_main, menubar1, "menubar1");
  GLADE_HOOKUP_OBJECT (window_main, menubar1_uiinfo[0].widget, "file1");
  GLADE_HOOKUP_OBJECT (window_main, file1_menu_uiinfo[0].widget, "new1");
  GLADE_HOOKUP_OBJECT (window_main, file1_menu_uiinfo[1].widget, "open1");
  GLADE_HOOKUP_OBJECT (window_main, file1_menu_uiinfo[2].widget, "save1");
  GLADE_HOOKUP_OBJECT (window_main, file1_menu_uiinfo[3].widget, "save_as1");
  GLADE_HOOKUP_OBJECT (window_main, file1_menu_uiinfo[4].widget, "separator3");
  GLADE_HOOKUP_OBJECT (window_main, file1_menu_uiinfo[5].widget, "quit1");
  GLADE_HOOKUP_OBJECT (window_main, menubar1_uiinfo[1].widget, "_8085");
  GLADE_HOOKUP_OBJECT (window_main, _8085_menu_uiinfo[0].widget, "reset1");
  GLADE_HOOKUP_OBJECT (window_main, reset1_menu_uiinfo[0].widget, "registers1");
  GLADE_HOOKUP_OBJECT (window_main, reset1_menu_uiinfo[1].widget, "flags1");
  GLADE_HOOKUP_OBJECT (window_main, reset1_menu_uiinfo[2].widget, "io_ports1");
  GLADE_HOOKUP_OBJECT (window_main, reset1_menu_uiinfo[3].widget, "main_memory1");
  GLADE_HOOKUP_OBJECT (window_main, reset1_menu_uiinfo[4].widget, "separator5");
  GLADE_HOOKUP_OBJECT (window_main, reset1_menu_uiinfo[5].widget, "reset_all1");
  GLADE_HOOKUP_OBJECT (window_main, menubar1_uiinfo[2].widget, "assembler1");
  GLADE_HOOKUP_OBJECT (window_main, assembler1_menu_uiinfo[0].widget, "assemble1");
  GLADE_HOOKUP_OBJECT (window_main, assembler1_menu_uiinfo[1].widget, "separator6");
  GLADE_HOOKUP_OBJECT (window_main, assembler1_menu_uiinfo[2].widget, "execute1");
  GLADE_HOOKUP_OBJECT (window_main, assembler1_menu_uiinfo[3].widget, "separator13");
  GLADE_HOOKUP_OBJECT (window_main, assembler1_menu_uiinfo[4].widget, "show_listing1");
  GLADE_HOOKUP_OBJECT (window_main, menubar1_uiinfo[3].widget, "debug1");
  GLADE_HOOKUP_OBJECT (window_main, debug1_menu_uiinfo[0].widget, "step_in1");
  GLADE_HOOKUP_OBJECT (window_main, debug1_menu_uiinfo[1].widget, "step_over1");
  GLADE_HOOKUP_OBJECT (window_main, debug1_menu_uiinfo[2].widget, "step_out1");
  GLADE_HOOKUP_OBJECT (window_main, debug1_menu_uiinfo[3].widget, "separator7");
  GLADE_HOOKUP_OBJECT (window_main, debug1_menu_uiinfo[4].widget, "breakpoints1");
  GLADE_HOOKUP_OBJECT (window_main, breakpoints1_menu_uiinfo[0].widget, "toggle_breakpoint1");
  GLADE_HOOKUP_OBJECT (window_main, breakpoints1_menu_uiinfo[1].widget, "separator8");
  GLADE_HOOKUP_OBJECT (window_main, breakpoints1_menu_uiinfo[2].widget, "clear_all_breakpoints1");
  GLADE_HOOKUP_OBJECT (window_main, debug1_menu_uiinfo[5].widget, "separator9");
  GLADE_HOOKUP_OBJECT (window_main, debug1_menu_uiinfo[6].widget, "stop_execution1");
  GLADE_HOOKUP_OBJECT (window_main, menubar1_uiinfo[4].widget, "help1");
  GLADE_HOOKUP_OBJECT (window_main, help1_menu_uiinfo[0].widget, "help2");
  GLADE_HOOKUP_OBJECT (window_main, help1_menu_uiinfo[1].widget, "separator11");
  GLADE_HOOKUP_OBJECT (window_main, help1_menu_uiinfo[2].widget, "_8085_manual1");
  GLADE_HOOKUP_OBJECT (window_main, help1_menu_uiinfo[3].widget, "assembler_reference1");
  GLADE_HOOKUP_OBJECT (window_main, help1_menu_uiinfo[4].widget, "separator10");
  GLADE_HOOKUP_OBJECT (window_main, help1_menu_uiinfo[5].widget, "about1");
  GLADE_HOOKUP_OBJECT (window_main, handlebox1, "handlebox1");
  GLADE_HOOKUP_OBJECT (window_main, toolbar1, "toolbar1");
  GLADE_HOOKUP_OBJECT (window_main, new1_t, "new1_t");
  GLADE_HOOKUP_OBJECT (window_main, open1_t, "open1_t");
  GLADE_HOOKUP_OBJECT (window_main, save1_t, "save1_t");
  GLADE_HOOKUP_OBJECT (window_main, save_as1_t, "save_as1_t");
  GLADE_HOOKUP_OBJECT (window_main, vseparator1, "vseparator1");
  GLADE_HOOKUP_OBJECT (window_main, assemble1_tb, "assemble1_tb");
  GLADE_HOOKUP_OBJECT (window_main, execute1_tb, "execute1_tb");
  GLADE_HOOKUP_OBJECT (window_main, vseparator2, "vseparator2");
  GLADE_HOOKUP_OBJECT (window_main, button7, "button7");
  GLADE_HOOKUP_OBJECT (window_main, button8, "button8");
  GLADE_HOOKUP_OBJECT (window_main, button9, "button9");
  GLADE_HOOKUP_OBJECT (window_main, vseparator3, "vseparator3");
  GLADE_HOOKUP_OBJECT (window_main, button11, "button11");
  GLADE_HOOKUP_OBJECT (window_main, stop_execution1_tb, "stop_execution1_tb");
  GLADE_HOOKUP_OBJECT (window_main, main_hpaned_left, "main_hpaned_left");
  GLADE_HOOKUP_OBJECT (window_main, vbox9, "vbox9");
  GLADE_HOOKUP_OBJECT (window_main, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (window_main, frame9, "frame9");
  GLADE_HOOKUP_OBJECT (window_main, table7, "table7");
  GLADE_HOOKUP_OBJECT (window_main, label107, "label107");
  GLADE_HOOKUP_OBJECT (window_main, label108, "label108");
  GLADE_HOOKUP_OBJECT (window_main, label109, "label109");
  GLADE_HOOKUP_OBJECT (window_main, label110, "label110");
  GLADE_HOOKUP_OBJECT (window_main, label111, "label111");
  GLADE_HOOKUP_OBJECT (window_main, label112, "label112");
  GLADE_HOOKUP_OBJECT (window_main, label113, "label113");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_a, "main_reg_a");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_b, "main_reg_b");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_c, "main_reg_c");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_d, "main_reg_d");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_e, "main_reg_e");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_h, "main_reg_h");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_l, "main_reg_l");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_pswh, "main_reg_pswh");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_pswl, "main_reg_pswl");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_pch, "main_reg_pch");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_pcl, "main_reg_pcl");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_sph, "main_reg_sph");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_spl, "main_reg_spl");
  GLADE_HOOKUP_OBJECT (window_main, main_reg_int_reg, "main_reg_int_reg");
  GLADE_HOOKUP_OBJECT (window_main, label106, "label106");
  GLADE_HOOKUP_OBJECT (window_main, hbox34, "hbox34");
  GLADE_HOOKUP_OBJECT (window_main, image365, "image365");
  GLADE_HOOKUP_OBJECT (window_main, label96, "label96");
  GLADE_HOOKUP_OBJECT (window_main, frame10, "frame10");
  GLADE_HOOKUP_OBJECT (window_main, table8, "table8");
  GLADE_HOOKUP_OBJECT (window_main, label129, "label129");
  GLADE_HOOKUP_OBJECT (window_main, label130, "label130");
  GLADE_HOOKUP_OBJECT (window_main, label131, "label131");
  GLADE_HOOKUP_OBJECT (window_main, label132, "label132");
  GLADE_HOOKUP_OBJECT (window_main, label133, "label133");
  GLADE_HOOKUP_OBJECT (window_main, main_flag_s, "main_flag_s");
  GLADE_HOOKUP_OBJECT (window_main, main_flag_z, "main_flag_z");
  GLADE_HOOKUP_OBJECT (window_main, main_flag_ac, "main_flag_ac");
  GLADE_HOOKUP_OBJECT (window_main, main_flag_p, "main_flag_p");
  GLADE_HOOKUP_OBJECT (window_main, main_flag_c, "main_flag_c");
  GLADE_HOOKUP_OBJECT (window_main, hbox35, "hbox35");
  GLADE_HOOKUP_OBJECT (window_main, image366, "image366");
  GLADE_HOOKUP_OBJECT (window_main, label163, "label163");
  GLADE_HOOKUP_OBJECT (window_main, frame12, "frame12");
  GLADE_HOOKUP_OBJECT (window_main, hbox29, "hbox29");
  GLADE_HOOKUP_OBJECT (window_main, vbox13, "vbox13");
  GLADE_HOOKUP_OBJECT (window_main, label154, "label154");
  GLADE_HOOKUP_OBJECT (window_main, main_entry_dec, "main_entry_dec");
  GLADE_HOOKUP_OBJECT (window_main, main_but_to_hex, "main_but_to_hex");
  GLADE_HOOKUP_OBJECT (window_main, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window_main, hbox30, "hbox30");
  GLADE_HOOKUP_OBJECT (window_main, image293, "image293");
  GLADE_HOOKUP_OBJECT (window_main, label156, "label156");
  GLADE_HOOKUP_OBJECT (window_main, vbox14, "vbox14");
  GLADE_HOOKUP_OBJECT (window_main, label155, "label155");
  GLADE_HOOKUP_OBJECT (window_main, main_entry_hex, "main_entry_hex");
  GLADE_HOOKUP_OBJECT (window_main, main_but_to_dec, "main_but_to_dec");
  GLADE_HOOKUP_OBJECT (window_main, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (window_main, hbox31, "hbox31");
  GLADE_HOOKUP_OBJECT (window_main, image294, "image294");
  GLADE_HOOKUP_OBJECT (window_main, label157, "label157");
  GLADE_HOOKUP_OBJECT (window_main, hbox38, "hbox38");
  GLADE_HOOKUP_OBJECT (window_main, image369, "image369");
  GLADE_HOOKUP_OBJECT (window_main, label153, "label153");
  GLADE_HOOKUP_OBJECT (window_main, vbox10, "vbox10");
  GLADE_HOOKUP_OBJECT (window_main, frame6, "frame6");
  GLADE_HOOKUP_OBJECT (window_main, vbox11, "vbox11");
  GLADE_HOOKUP_OBJECT (window_main, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (window_main, main_io_spin, "main_io_spin");
  GLADE_HOOKUP_OBJECT (window_main, main_io_entry, "main_io_entry");
  GLADE_HOOKUP_OBJECT (window_main, main_io_update, "main_io_update");
  GLADE_HOOKUP_OBJECT (window_main, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (window_main, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (window_main, image226, "image226");
  GLADE_HOOKUP_OBJECT (window_main, label139, "label139");
  GLADE_HOOKUP_OBJECT (window_main, hbox36, "hbox36");
  GLADE_HOOKUP_OBJECT (window_main, image367, "image367");
  GLADE_HOOKUP_OBJECT (window_main, label164, "label164");
  GLADE_HOOKUP_OBJECT (window_main, frame8, "frame8");
  GLADE_HOOKUP_OBJECT (window_main, vbox12, "vbox12");
  GLADE_HOOKUP_OBJECT (window_main, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (window_main, main_mem_spin, "main_mem_spin");
  GLADE_HOOKUP_OBJECT (window_main, main_mem_entry, "main_mem_entry");
  GLADE_HOOKUP_OBJECT (window_main, main_mem_update, "main_mem_update");
  GLADE_HOOKUP_OBJECT (window_main, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (window_main, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (window_main, image227, "image227");
  GLADE_HOOKUP_OBJECT (window_main, label140, "label140");
  GLADE_HOOKUP_OBJECT (window_main, hbox37, "hbox37");
  GLADE_HOOKUP_OBJECT (window_main, image368, "image368");
  GLADE_HOOKUP_OBJECT (window_main, label165, "label165");
  GLADE_HOOKUP_OBJECT (window_main, main_vpaned_msg, "main_vpaned_msg");
  GLADE_HOOKUP_OBJECT (window_main, main_hpaned_data, "main_hpaned_data");
  GLADE_HOOKUP_OBJECT (window_main, main_vbox_center, "main_vbox_center");
  GLADE_HOOKUP_OBJECT (window_main, hbox24, "hbox24");
  GLADE_HOOKUP_OBJECT (window_main, label147, "label147");
  GLADE_HOOKUP_OBJECT (window_main, main_entry_sa, "main_entry_sa");
  GLADE_HOOKUP_OBJECT (window_main, notebook5, "notebook5");
  GLADE_HOOKUP_OBJECT (window_main, main_frame_data, "main_frame_data");
  GLADE_HOOKUP_OBJECT (window_main, main_data_scroll, "main_data_scroll");
  GLADE_HOOKUP_OBJECT (window_main, label150, "label150");
  GLADE_HOOKUP_OBJECT (window_main, hbox25, "hbox25");
  GLADE_HOOKUP_OBJECT (window_main, image232, "image232");
  GLADE_HOOKUP_OBJECT (window_main, label148, "label148");
  GLADE_HOOKUP_OBJECT (window_main, frame11, "frame11");
  GLADE_HOOKUP_OBJECT (window_main, main_stack_scroll, "main_stack_scroll");
  GLADE_HOOKUP_OBJECT (window_main, label152, "label152");
  GLADE_HOOKUP_OBJECT (window_main, hbox26, "hbox26");
  GLADE_HOOKUP_OBJECT (window_main, image233, "image233");
  GLADE_HOOKUP_OBJECT (window_main, label149, "label149");
  GLADE_HOOKUP_OBJECT (window_main, frame14, "frame14");
  GLADE_HOOKUP_OBJECT (window_main, main_keypad_scroll, "main_keypad_scroll");
  GLADE_HOOKUP_OBJECT (window_main, label169, "label169");
  GLADE_HOOKUP_OBJECT (window_main, hbox40, "hbox40");
  GLADE_HOOKUP_OBJECT (window_main, image371, "image371");
  GLADE_HOOKUP_OBJECT (window_main, label168, "label168");
  GLADE_HOOKUP_OBJECT (window_main, main_appbar, "main_appbar");
  GLADE_HOOKUP_OBJECT_NO_REF (window_main, tooltips, "tooltips");

  gtk_widget_grab_focus (main_entry_sa);
  return window_main;
}

GtkWidget*
create_dialog_about (void)
{
  const gchar *authors[] = {
    "Main programmer and founder:",
    "Sridhar Ratna (srid@nearfar.org)",
    NULL
  };
  const gchar *documenters[] = {
    "Sridhar Ratna (srid@nearfar.org)",
    NULL
  };
  /* TRANSLATORS: Replace this string with your names, one name per line. */
  gchar *translators = _("translator_credits");
  GdkPixbuf *dialog_about_logo_pixbuf;
  GtkWidget *dialog_about;
  GdkPixbuf *dialog_about_icon_pixbuf;

  if (!strcmp (translators, "translator_credits"))
    translators = NULL;
  dialog_about_logo_pixbuf = create_pixbuf ("gnusim8085_icon.png");
  dialog_about = gnome_about_new ("GNUSim8085", VERSION,
                        _("Copyright (C) 2003 Sridhar Ratna"),
                        _("8085 Microprocessor Simulator\nhttp://gnusim8085.sourceforge.net/"),
                        authors,
                        documenters,
                        translators,
                        dialog_about_logo_pixbuf);
  gtk_container_set_border_width (GTK_CONTAINER (dialog_about), 5);
  gtk_window_set_destroy_with_parent (GTK_WINDOW (dialog_about), TRUE);
  dialog_about_icon_pixbuf = create_pixbuf ("gnusim8085_icon.png");
  if (dialog_about_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog_about), dialog_about_icon_pixbuf);
      gdk_pixbuf_unref (dialog_about_icon_pixbuf);
    }

  g_signal_connect ((gpointer) dialog_about, "close",
                    G_CALLBACK (gtk_widget_hide),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_about, dialog_about, "dialog_about");

  return dialog_about;
}

GtkWidget*
create_window_listing (void)
{
  GtkWidget *window_listing;
  GdkPixbuf *window_listing_icon_pixbuf;
  GtkWidget *listing_vbox;
  GtkWidget *hbuttonbox1;
  GtkWidget *listing_save;
  GtkWidget *alignment11;
  GtkWidget *hbox39;
  GtkWidget *image370;
  GtkWidget *label167;

  window_listing = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_listing), _("Assembler Listing"));
  gtk_window_set_position (GTK_WINDOW (window_listing), GTK_WIN_POS_CENTER);
  window_listing_icon_pixbuf = create_pixbuf ("gnusim8085_icon.png");
  if (window_listing_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window_listing), window_listing_icon_pixbuf);
      gdk_pixbuf_unref (window_listing_icon_pixbuf);
    }

  listing_vbox = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (listing_vbox);
  gtk_container_add (GTK_CONTAINER (window_listing), listing_vbox);
  gtk_container_set_border_width (GTK_CONTAINER (listing_vbox), 5);

  hbuttonbox1 = gtk_hbutton_box_new ();
  gtk_widget_show (hbuttonbox1);
  gtk_box_pack_start (GTK_BOX (listing_vbox), hbuttonbox1, FALSE, FALSE, 0);

  listing_save = gtk_button_new ();
  gtk_widget_show (listing_save);
  gtk_container_add (GTK_CONTAINER (hbuttonbox1), listing_save);
  GTK_WIDGET_SET_FLAGS (listing_save, GTK_CAN_DEFAULT);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (listing_save), alignment11);

  hbox39 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox39);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox39);

  image370 = gtk_image_new_from_stock ("gtk-save", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image370);
  gtk_box_pack_start (GTK_BOX (hbox39), image370, FALSE, FALSE, 0);

  label167 = gtk_label_new_with_mnemonic (_("Save to file"));
  gtk_widget_show (label167);
  gtk_box_pack_start (GTK_BOX (hbox39), label167, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label167), GTK_JUSTIFY_LEFT);

  g_signal_connect ((gpointer) listing_save, "clicked",
                    G_CALLBACK (on_listing_save_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_listing, window_listing, "window_listing");
  GLADE_HOOKUP_OBJECT (window_listing, listing_vbox, "listing_vbox");
  GLADE_HOOKUP_OBJECT (window_listing, hbuttonbox1, "hbuttonbox1");
  GLADE_HOOKUP_OBJECT (window_listing, listing_save, "listing_save");
  GLADE_HOOKUP_OBJECT (window_listing, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (window_listing, hbox39, "hbox39");
  GLADE_HOOKUP_OBJECT (window_listing, image370, "image370");
  GLADE_HOOKUP_OBJECT (window_listing, label167, "label167");

  return window_listing;
}

GtkWidget*
create_window_start (void)
{
  GtkWidget *window_start;
  GdkPixbuf *window_start_icon_pixbuf;
  GtkWidget *vbox15;
  GtkWidget *frame13;
  GtkWidget *vbox16;
  GtkWidget *vbox17;
  GtkWidget *label159;
  GtkWidget *start_but_tutorial;
  GtkWidget *alignment9;
  GtkWidget *hbox32;
  GtkWidget *image310;
  GtkWidget *label160;
  GtkWidget *vbox18;
  GtkWidget *label161;
  GtkWidget *start_but_open;
  GtkWidget *alignment10;
  GtkWidget *hbox33;
  GtkWidget *image311;
  GtkWidget *label162;
  GtkWidget *label158;
  GtkWidget *start_but_close;
  GtkWidget *label166;
  GtkTooltips *tooltips;

  tooltips = gtk_tooltips_new ();

  window_start = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window_start), _("GNUSim8085 start with dialog"));
  gtk_window_set_position (GTK_WINDOW (window_start), GTK_WIN_POS_CENTER);
  gtk_window_set_modal (GTK_WINDOW (window_start), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (window_start), FALSE);
  window_start_icon_pixbuf = create_pixbuf ("gnusim8085_icon.png");
  if (window_start_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (window_start), window_start_icon_pixbuf);
      gdk_pixbuf_unref (window_start_icon_pixbuf);
    }

  vbox15 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox15);
  gtk_container_add (GTK_CONTAINER (window_start), vbox15);
  gtk_container_set_border_width (GTK_CONTAINER (vbox15), 5);

  frame13 = gtk_frame_new (NULL);
  gtk_widget_show (frame13);
  gtk_box_pack_start (GTK_BOX (vbox15), frame13, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (frame13), 5);

  vbox16 = gtk_vbox_new (FALSE, 0);
  gtk_widget_show (vbox16);
  gtk_container_add (GTK_CONTAINER (frame13), vbox16);

  vbox17 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox17);
  gtk_box_pack_start (GTK_BOX (vbox16), vbox17, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox17), 10);

  label159 = gtk_label_new (_("1. How to use this simulator?"));
  gtk_widget_show (label159);
  gtk_box_pack_start (GTK_BOX (vbox17), label159, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label159), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label159), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label159), 0, 0.5);

  start_but_tutorial = gtk_button_new ();
  gtk_widget_show (start_but_tutorial);
  gtk_box_pack_start (GTK_BOX (vbox17), start_but_tutorial, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, start_but_tutorial, _("A short tutorial on writing assembly code!"), NULL);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (start_but_tutorial), alignment9);

  hbox32 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox32);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox32);

  image310 = gtk_image_new_from_stock ("gtk-help", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image310);
  gtk_box_pack_start (GTK_BOX (hbox32), image310, FALSE, FALSE, 0);

  label160 = gtk_label_new_with_mnemonic (_("Tutorial"));
  gtk_widget_show (label160);
  gtk_box_pack_start (GTK_BOX (hbox32), label160, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label160), GTK_JUSTIFY_LEFT);

  vbox18 = gtk_vbox_new (FALSE, 5);
  gtk_widget_show (vbox18);
  gtk_box_pack_start (GTK_BOX (vbox16), vbox18, FALSE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (vbox18), 10);

  label161 = gtk_label_new (_("2. Open an existing assembly program."));
  gtk_widget_show (label161);
  gtk_box_pack_start (GTK_BOX (vbox18), label161, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label161), GTK_JUSTIFY_LEFT);
  gtk_label_set_line_wrap (GTK_LABEL (label161), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label161), 0, 0.5);

  start_but_open = gtk_button_new ();
  gtk_widget_show (start_but_open);
  gtk_box_pack_start (GTK_BOX (vbox18), start_but_open, FALSE, FALSE, 0);
  gtk_tooltips_set_tip (tooltips, start_but_open, _("Open an already saved program"), NULL);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (start_but_open), alignment10);

  hbox33 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox33);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox33);

  image311 = gtk_image_new_from_stock ("gtk-open", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image311);
  gtk_box_pack_start (GTK_BOX (hbox33), image311, FALSE, FALSE, 0);

  label162 = gtk_label_new_with_mnemonic (_("Open program"));
  gtk_widget_show (label162);
  gtk_box_pack_start (GTK_BOX (hbox33), label162, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label162), GTK_JUSTIFY_LEFT);

  label158 = gtk_label_new (_("What do you want to do now?"));
  gtk_widget_show (label158);
  gtk_frame_set_label_widget (GTK_FRAME (frame13), label158);
  gtk_label_set_justify (GTK_LABEL (label158), GTK_JUSTIFY_LEFT);

  start_but_close = gtk_button_new_from_stock ("gtk-close");
  gtk_widget_show (start_but_close);
  gtk_box_pack_end (GTK_BOX (vbox15), start_but_close, FALSE, FALSE, 0);
  GTK_WIDGET_SET_FLAGS (start_but_close, GTK_CAN_DEFAULT);

  label166 = gtk_label_new (_("Don't forget to read the documentation \ngiven in \"doc\" directory."));
  gtk_widget_show (label166);
  gtk_box_pack_start (GTK_BOX (vbox15), label166, FALSE, FALSE, 5);

  g_signal_connect ((gpointer) window_start, "delete_event",
                    G_CALLBACK (gtk_widget_destroy),
                    NULL);
  g_signal_connect ((gpointer) start_but_tutorial, "clicked",
                    G_CALLBACK (on_start_but_tutorial_clicked),
                    NULL);
  g_signal_connect ((gpointer) start_but_open, "clicked",
                    G_CALLBACK (on_start_but_open_clicked),
                    NULL);
  g_signal_connect ((gpointer) start_but_close, "clicked",
                    G_CALLBACK (on_start_but_close_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window_start, window_start, "window_start");
  GLADE_HOOKUP_OBJECT (window_start, vbox15, "vbox15");
  GLADE_HOOKUP_OBJECT (window_start, frame13, "frame13");
  GLADE_HOOKUP_OBJECT (window_start, vbox16, "vbox16");
  GLADE_HOOKUP_OBJECT (window_start, vbox17, "vbox17");
  GLADE_HOOKUP_OBJECT (window_start, label159, "label159");
  GLADE_HOOKUP_OBJECT (window_start, start_but_tutorial, "start_but_tutorial");
  GLADE_HOOKUP_OBJECT (window_start, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (window_start, hbox32, "hbox32");
  GLADE_HOOKUP_OBJECT (window_start, image310, "image310");
  GLADE_HOOKUP_OBJECT (window_start, label160, "label160");
  GLADE_HOOKUP_OBJECT (window_start, vbox18, "vbox18");
  GLADE_HOOKUP_OBJECT (window_start, label161, "label161");
  GLADE_HOOKUP_OBJECT (window_start, start_but_open, "start_but_open");
  GLADE_HOOKUP_OBJECT (window_start, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (window_start, hbox33, "hbox33");
  GLADE_HOOKUP_OBJECT (window_start, image311, "image311");
  GLADE_HOOKUP_OBJECT (window_start, label162, "label162");
  GLADE_HOOKUP_OBJECT (window_start, label158, "label158");
  GLADE_HOOKUP_OBJECT (window_start, start_but_close, "start_but_close");
  GLADE_HOOKUP_OBJECT (window_start, label166, "label166");
  GLADE_HOOKUP_OBJECT_NO_REF (window_start, tooltips, "tooltips");

  gtk_widget_grab_focus (start_but_close);
  return window_start;
}

GtkWidget*
create_dialog_isymbol (void)
{
  GtkWidget *dialog_isymbol;
  GdkPixbuf *dialog_isymbol_icon_pixbuf;
  GtkWidget *dialog_vbox1;
  GtkWidget *isymbol_vbox;
  GtkWidget *label170;
  GtkWidget *hbox44;
  GtkWidget *label171;
  GtkWidget *entry1;
  GtkWidget *isymbol_entry;
  GtkWidget *hbox45;
  GtkWidget *label174;
  GtkWidget *isymbol_variables;
  GtkWidget *isymbol_variables_entry;
  GtkWidget *hbox46;
  GtkWidget *label175;
  GtkWidget *isymbol_labels;
  GtkWidget *isymbol_functions_entry;
  GtkWidget *hbox47;
  GtkWidget *label176;
  GtkWidget *isymbol_macros;
  GtkWidget *isymbol_macros_entry;
  GtkWidget *dialog_action_area1;
  GtkWidget *cancelbutton1;
  GtkWidget *okbutton1;

  dialog_isymbol = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_isymbol), _("Choose a symbol"));
  gtk_window_set_position (GTK_WINDOW (dialog_isymbol), GTK_WIN_POS_MOUSE);
  gtk_window_set_modal (GTK_WINDOW (dialog_isymbol), TRUE);
  gtk_window_set_resizable (GTK_WINDOW (dialog_isymbol), FALSE);
  dialog_isymbol_icon_pixbuf = create_pixbuf ("gnusim8085_icon.png");
  if (dialog_isymbol_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog_isymbol), dialog_isymbol_icon_pixbuf);
      gdk_pixbuf_unref (dialog_isymbol_icon_pixbuf);
    }

  dialog_vbox1 = GTK_DIALOG (dialog_isymbol)->vbox;
  gtk_widget_show (dialog_vbox1);

  isymbol_vbox = gtk_vbox_new (FALSE, 2);
  gtk_widget_show (isymbol_vbox);
  gtk_box_pack_start (GTK_BOX (dialog_vbox1), isymbol_vbox, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (isymbol_vbox), 5);

  label170 = gtk_label_new (_("Enter a symbol or choose one from the lists"));
  gtk_widget_show (label170);
  gtk_box_pack_start (GTK_BOX (isymbol_vbox), label170, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label170), GTK_JUSTIFY_LEFT);

  hbox44 = gtk_hbox_new (FALSE, 5);
  gtk_widget_show (hbox44);
  gtk_box_pack_start (GTK_BOX (isymbol_vbox), hbox44, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox44), 2);

  label171 = gtk_label_new (_("Enter Symbol"));
  gtk_widget_show (label171);
  gtk_box_pack_start (GTK_BOX (hbox44), label171, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label171), GTK_JUSTIFY_LEFT);

  entry1 = gnome_entry_new (NULL);
  gtk_widget_show (entry1);
  gtk_box_pack_start (GTK_BOX (hbox44), entry1, TRUE, TRUE, 0);

  isymbol_entry = gnome_entry_gtk_entry (GNOME_ENTRY (entry1));
  gtk_widget_show (isymbol_entry);

  hbox45 = gtk_hbox_new (TRUE, 5);
  gtk_widget_show (hbox45);
  gtk_box_pack_start (GTK_BOX (isymbol_vbox), hbox45, FALSE, FALSE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox45), 2);

  label174 = gtk_label_new (_("Variables List"));
  gtk_widget_show (label174);
  gtk_box_pack_start (GTK_BOX (hbox45), label174, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label174), GTK_JUSTIFY_LEFT);

  isymbol_variables = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (isymbol_variables)->popwin),
                     "GladeParentKey", isymbol_variables);
  gtk_widget_show (isymbol_variables);
  gtk_box_pack_start (GTK_BOX (hbox45), isymbol_variables, TRUE, TRUE, 0);
  gtk_combo_set_case_sensitive (GTK_COMBO (isymbol_variables), TRUE);

  isymbol_variables_entry = GTK_COMBO (isymbol_variables)->entry;
  gtk_widget_show (isymbol_variables_entry);
  gtk_editable_set_editable (GTK_EDITABLE (isymbol_variables_entry), FALSE);

  hbox46 = gtk_hbox_new (TRUE, 5);
  gtk_widget_show (hbox46);
  gtk_box_pack_start (GTK_BOX (isymbol_vbox), hbox46, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox46), 2);

  label175 = gtk_label_new (_("Functions List"));
  gtk_widget_show (label175);
  gtk_box_pack_start (GTK_BOX (hbox46), label175, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label175), GTK_JUSTIFY_LEFT);

  isymbol_labels = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (isymbol_labels)->popwin),
                     "GladeParentKey", isymbol_labels);
  gtk_widget_show (isymbol_labels);
  gtk_box_pack_start (GTK_BOX (hbox46), isymbol_labels, TRUE, TRUE, 0);
  gtk_combo_set_case_sensitive (GTK_COMBO (isymbol_labels), TRUE);

  isymbol_functions_entry = GTK_COMBO (isymbol_labels)->entry;
  gtk_widget_show (isymbol_functions_entry);
  gtk_editable_set_editable (GTK_EDITABLE (isymbol_functions_entry), FALSE);

  hbox47 = gtk_hbox_new (TRUE, 5);
  gtk_widget_show (hbox47);
  gtk_box_pack_start (GTK_BOX (isymbol_vbox), hbox47, TRUE, TRUE, 0);
  gtk_container_set_border_width (GTK_CONTAINER (hbox47), 2);

  label176 = gtk_label_new (_("Macros List"));
  gtk_widget_show (label176);
  gtk_box_pack_start (GTK_BOX (hbox47), label176, FALSE, FALSE, 0);
  gtk_label_set_justify (GTK_LABEL (label176), GTK_JUSTIFY_LEFT);

  isymbol_macros = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (isymbol_macros)->popwin),
                     "GladeParentKey", isymbol_macros);
  gtk_widget_show (isymbol_macros);
  gtk_box_pack_start (GTK_BOX (hbox47), isymbol_macros, TRUE, TRUE, 0);
  gtk_combo_set_case_sensitive (GTK_COMBO (isymbol_macros), TRUE);

  isymbol_macros_entry = GTK_COMBO (isymbol_macros)->entry;
  gtk_widget_show (isymbol_macros_entry);
  gtk_editable_set_editable (GTK_EDITABLE (isymbol_macros_entry), FALSE);

  dialog_action_area1 = GTK_DIALOG (dialog_isymbol)->action_area;
  gtk_widget_show (dialog_action_area1);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area1), GTK_BUTTONBOX_END);

  cancelbutton1 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_isymbol), cancelbutton1, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton1, GTK_CAN_DEFAULT);

  okbutton1 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton1);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_isymbol), okbutton1, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton1, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_isymbol, dialog_isymbol, "dialog_isymbol");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_isymbol, dialog_vbox1, "dialog_vbox1");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, isymbol_vbox, "isymbol_vbox");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, label170, "label170");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, hbox44, "hbox44");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, label171, "label171");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, isymbol_entry, "isymbol_entry");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, hbox45, "hbox45");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, label174, "label174");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, isymbol_variables, "isymbol_variables");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, isymbol_variables_entry, "isymbol_variables_entry");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, hbox46, "hbox46");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, label175, "label175");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, isymbol_labels, "isymbol_labels");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, isymbol_functions_entry, "isymbol_functions_entry");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, hbox47, "hbox47");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, label176, "label176");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, isymbol_macros, "isymbol_macros");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, isymbol_macros_entry, "isymbol_macros_entry");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_isymbol, dialog_action_area1, "dialog_action_area1");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, cancelbutton1, "cancelbutton1");
  GLADE_HOOKUP_OBJECT (dialog_isymbol, okbutton1, "okbutton1");

  gtk_widget_grab_focus (isymbol_entry);
  return dialog_isymbol;
}

GtkWidget*
create_dialog_ireg (void)
{
  GtkWidget *dialog_ireg;
  GdkPixbuf *dialog_ireg_icon_pixbuf;
  GtkWidget *dialog_vbox2;
  GtkWidget *ireg;
  GtkWidget *ireg_entry;
  GtkWidget *dialog_action_area2;
  GtkWidget *cancelbutton2;
  GtkWidget *okbutton2;

  dialog_ireg = gtk_dialog_new ();
  gtk_window_set_title (GTK_WINDOW (dialog_ireg), _("Choose a register"));
  gtk_window_set_position (GTK_WINDOW (dialog_ireg), GTK_WIN_POS_MOUSE);
  gtk_window_set_resizable (GTK_WINDOW (dialog_ireg), FALSE);
  dialog_ireg_icon_pixbuf = create_pixbuf ("gnusim8085_icon.png");
  if (dialog_ireg_icon_pixbuf)
    {
      gtk_window_set_icon (GTK_WINDOW (dialog_ireg), dialog_ireg_icon_pixbuf);
      gdk_pixbuf_unref (dialog_ireg_icon_pixbuf);
    }

  dialog_vbox2 = GTK_DIALOG (dialog_ireg)->vbox;
  gtk_widget_show (dialog_vbox2);

  ireg = gtk_combo_new ();
  g_object_set_data (G_OBJECT (GTK_COMBO (ireg)->popwin),
                     "GladeParentKey", ireg);
  gtk_widget_show (ireg);
  gtk_box_pack_start (GTK_BOX (dialog_vbox2), ireg, FALSE, FALSE, 0);
  gtk_combo_set_value_in_list (GTK_COMBO (ireg), TRUE, FALSE);

  ireg_entry = GTK_COMBO (ireg)->entry;
  gtk_widget_show (ireg_entry);

  dialog_action_area2 = GTK_DIALOG (dialog_ireg)->action_area;
  gtk_widget_show (dialog_action_area2);
  gtk_button_box_set_layout (GTK_BUTTON_BOX (dialog_action_area2), GTK_BUTTONBOX_END);

  cancelbutton2 = gtk_button_new_from_stock ("gtk-cancel");
  gtk_widget_show (cancelbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ireg), cancelbutton2, GTK_RESPONSE_CANCEL);
  GTK_WIDGET_SET_FLAGS (cancelbutton2, GTK_CAN_DEFAULT);

  okbutton2 = gtk_button_new_from_stock ("gtk-ok");
  gtk_widget_show (okbutton2);
  gtk_dialog_add_action_widget (GTK_DIALOG (dialog_ireg), okbutton2, GTK_RESPONSE_OK);
  GTK_WIDGET_SET_FLAGS (okbutton2, GTK_CAN_DEFAULT);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ireg, dialog_ireg, "dialog_ireg");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ireg, dialog_vbox2, "dialog_vbox2");
  GLADE_HOOKUP_OBJECT (dialog_ireg, ireg, "ireg");
  GLADE_HOOKUP_OBJECT (dialog_ireg, ireg_entry, "ireg_entry");
  GLADE_HOOKUP_OBJECT_NO_REF (dialog_ireg, dialog_action_area2, "dialog_action_area2");
  GLADE_HOOKUP_OBJECT (dialog_ireg, cancelbutton2, "cancelbutton2");
  GLADE_HOOKUP_OBJECT (dialog_ireg, okbutton2, "okbutton2");

  return dialog_ireg;
}
