/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include <libintl.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>
#include <gtk/gtk.h>

#define _(String) gettext (String)
#define N_(String) (String)

/*
 * Public Functions.
 */

/*
 * This function returns a widget in a component created by Glade.
 * Call it with the toplevel widget in the component (i.e. a window/dialog),
 * or alternatively any widget in the component, and the name of the widget
 * you want returned.
 */
GtkWidget*  lookup_widget              (GtkWidget       *widget,
                                        const gchar     *widget_name);

/*
 * This function returns a action widget in a component.
 * Call it with the toplevel widget in the component (i.e. a window/dialog),
 * or alternatively any widget in the component, and the name of the widget
 * you want returned.
 */
GtkAction*  lookup_action_widget              (GtkWidget       *widget,
											   const gchar     *widget_name);


/*
 * Private Functions.
 */

/* This is used to create the pixbufs used in the interface. */
GdkPixbuf*  create_pixbuf              (const gchar     *filename);

/* This is used to read authors from AUTHORS file. */
gchar**  read_authors ();

