name: Build Verification

on:
  push:
    branches:
      - 'master'
      - 'ghatrial'
  pull_request:
    branches: [ "master" ]

jobs:
  build-linux:

    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libgtksourceview-3.0-dev gettext discount meson
    - name: Configure
      run: meson builddir
    - name: Build
      run: cd builddir && ninja

  build-macos:

    runs-on: macos-14-large
    continue-on-error: true

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Install build dependencies
      run: |
        brew unlink python
        brew link --overwrite python
        brew update
        brew upgrade
        brew config
        brew tap onkarshinde/gnusim8085-bundle
        brew install --build-from-source onkarshinde/gnusim8085-bundle/gdk-pixbuf
        brew bundle
        brew info gtksourceview3
        brew --prefix gtksourceview3
        brew link --force gettext
    - name: Configure
      run: |
        meson --prefix=`pwd`/macosdist/GNUSim8085.app --bindir=Contents/MacOS --datadir=Contents/Resources --localedir=Contents/Resources/locale --mandir=Contents/SharedSupport -Dbuild-macos-app=true macosdist
    - name: Build
      run: |
        cd macosdist && ninja install && shasum -a 256 *.zip && cd ..
        otool -L macosdist/GNUSim8085.app/Contents/MacOS/gnusim8085
        otool -L macosdist/GNUSim8085.app/Contents/libs/*.dylib
        otool -L macosdist/GNUSim8085.app/Contents/libs/gdk-pixbuf-2.0/2.10.0/loaders/*.so
        otool -L macosdist/GNUSim8085.app/Contents/libs/gdk-pixbuf-2.0/2.10.0/loaders/*.dylib

  build-windows:

    runs-on: ubuntu-latest

    steps:
    - name: Setup podman
      run: |
        sudo apt-get update
        sudo apt-get -y install podman
        podman pull fedora:42
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        path: 'red_amber'
    - name: Create container and build code
      run: |
        {
            echo 'FROM fedora:42'
            echo 'RUN dnf -y update'
            echo 'RUN dnf -y install gettext mingw32-gcc mingw32-gtksourceview3 mingw32-nsis meson discount'
            echo 'RUN dnf clean all'
            echo 'RUN rpm -ql mingw32-bzip2'
            echo 'COPY red_amber red_amber'
            echo 'WORKDIR /red_amber'
            echo 'RUN meson builddir --prefix=/ --cross-file meson_cross_win32.txt'
            echo 'RUN cd builddir && ninja && DESTDIR=`pwd`/win32 ninja install && makensis installer.nsi'
        } > podmanfile
        podman build -f ./podmanfile

